services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file: "/sgoinfre/goinfre/Perso/jiglesia/env/.env.red-tetris"
    depends_on:
      - postgres
    networks:
      - default

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: "/sgoinfre/goinfre/Perso/jiglesia/env/.env.red-tetris"
    networks:
      - default

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - REACT_APP_DOCKER=true
    depends_on:
      - server
    networks:
      - default
  
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - '5050:80'
    env_file: "/sgoinfre/goinfre/Perso/jiglesia/env/.env.red-tetris"

volumes:
  postgres_data:
    driver: local

networks:
  default:
    driver: bridge